import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import QueryProvider from '@/libs/react-query';
import ToastifyComponent from '@/libs/react-toastify';
import React from 'react';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <QueryProvider>
          {children}

          <ToastifyComponent />
        </QueryProvider>
      </body>
    </html>
  );
}
